- name: "Post ambari blueprint"
  uri:
    url: http://115.146.86.215:8080/api/v1/blueprints/team40_cluster?validate_topology=false
    method: POST
    user: admin
    password: admin
    headers: 
      X-Requested-By: "ambari"
    body: "{{ lookup('file','inventory/files/blueprint.json') }}"
    force_basic_auth: yes
    status_code: 201
    body_format: raw


- name: "Post ambari create cluster"
  uri:
    url: http://115.146.86.215:8080/api/v1/clusters/team40_cluster
    method: POST
    user: admin
    password: admin
    headers: 
      X-Requested-By: "ambari"
    body: "{{ lookup('file','inventory/files/cluster.json') }}"
    force_basic_auth: yes
    status_code: 201
    body_format: raw


- name: "Post ambari add node to cluster"
  uri:
    url: http://115.146.86.215:8080/api/v1/clusters/team40_cluster/hosts
    method: POST
    user: admin
    password: admin
    headers: 
      X-Requested-By: "ambari"
    body: "{{ lookup('file','inventory/files/add_host.json') }}"
    force_basic_auth: yes
    status_code: 201
    body_format: raw
