- name: Download Ambari repo list
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/ubuntu16/2.x/updates/2.6.1.5/ambari.list
    dest: /etc/apt/sources.list.d/ambari.list
    mode: 0755


- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: B9733A7A07513CAD
    state: present


- name: Update apt packages 
  become: true
  apt:
    update_cache: yes



- name: Install list of postgres
  apt: name={{item}} state=present
  with_items:
       - postgresql
       - postgresql-contrib
       - libpostgresql-jdbc-java


- name: Install  ambari-server
  apt: name={{item}} state=present
  with_items:
       - ambari-server